### ISSUE TITLE
Can you provide the test result (all txt files) on the validation set?

### ISSUE THREAD

**Issue by detectRecog** [mileyan/pseudo_lidar#14]
I want to carry out a more detailed comparison with your method. If you can provide these detection txt files on the validation set. It would be very helpful. 

Thank you. Hope you receive more citations.

**Comment by detectRecog** [comment]
Following the steps in this repo, I successfully get the results. The performance has been checked. Shared with you guys. 

链接: https://pan.baidu.com/s/1V6NuwQCTYKdpxZkfvW74YQ 提取码: cf6y 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by mileyan** [comment]
You can download them from https://github.com/mileyan/pseudo_lidar/blob/master/README.md#results
