### ISSUE TITLE
The test results

### ISSUE THREAD

**Issue by sshan-zhao** [mileyan/pseudo_lidar#17]
Hi,
It is a very nice work and thanks for releasing the code!!!
I have a question about the test results in the [leaderboard](http://www.cvlibs.net/datasets/kitti/eval_object.php?obj_benchmark=3d). I find you submitted two results, namely Pseudo-LiDAR (the result in the paper) and Pseudo-LiDAR-V2.  Compared with Pseudo-LiDAR, the second version improves a lot, so I am really interested in what you did to make the performance better. 
Thanks a lot.

**Comment by mileyan** [comment]
Pseudo-LIDAR V2 is one of our new models. You can download the paper from https://arxiv.org/abs/1906.06310 .
