### ISSUE TITLE
Unable to unzip the the pseudo-LiDAR point clouds on Google drive

### ISSUE THREAD

**Issue by Raahul-Singh** [mileyan/pseudo_lidar#21]
On trying, ``read error`` is reported.

**Comment by mileyan** [comment]
Hi, is the link correct? It is https://drive.google.com/file/d/10txZOtKk_aY3B7AhHjJPMCiRf5pP62nV/view?usp=sharing. I have downloaded it on my local laptop and it worked well. If you still cannot unzip it, I can try to upload it to some other cloud. Please let me know.

**Comment by Raahul-Singh** [comment]
Thank you so much. It is working now. i believe it was some issue with the unzip-per itself.  :sweat_smile:
