### ISSUE TITLE
your pre-trained AVOD model doesn't work

### ISSUE THREAD

**Issue by sarimmehdi** [mileyan/pseudo_lidar#24]
I ran the AVOD code but I get a "no checkpoint error". I did everything as was explained on the AVOD github. Please tell me how to make your AVOD pre-trained checkpoint work. This issue is also encountered here: https://github.com/mileyan/pseudo_lidar/issues/19 and remains unanswered

**Comment by mileyan** [comment]
Hi Sarimmehdi,

Sorry for hearing about it. To make it more convenient, I have modified the avod code a little bit. You can download the code from https://github.com/mileyan/avod_pl. I have tested it. Please message me if you have any questions after you trying it.

**Comment by sarimmehdi** [comment]
Thank you very much. It worked!
