### ISSUE TITLE
ModuleNotFoundError: No module named 'submodule'

### ISSUE THREAD

**Issue by sarimmehdi** [mileyan/pseudo_lidar#25]
I followed all your instructions but I still get the above error when I run the following command in Anaconda
`python ./psmnet/submission.py --loadmodel ./psmnet/kitti_3d/finetune_300.tar --datapath ./media/sarim/7AF2CEB6F2CE7643/datasets/kitti/object/training/ --save_path ./media/sarim/7AF2CEB6F2CE7643/datasets/kitti/object/training/predict_disparity`

The full error log is:
```
Traceback (most recent call last):
  File "./psmnet/submission.py", line 20, in <module>
    from models import *
  File "/home/sarim/pseudo_lidar/psmnet/models/__init__.py", line 1, in <module>
    from .basic import PSMNet as basic
  File "/home/sarim/pseudo_lidar/psmnet/models/basic.py", line 8, in <module>
    from submodule import *
ModuleNotFoundError: No module named 'submodule'
```

**Comment by Teeemio** [comment]
Hi, did you solve this problem?

**Comment by mileyan** [comment]
Hi @Teeemio, could you check your python version? This code needs python 2.7

**Comment by Cli98** [comment]
@mileyan @Teeemio You can fix this by using relative import. Nothing to do with python version.
Change to "from .submodule import *"
