### ISSUE TITLE
finetune_300.tar

### ISSUE THREAD

**Issue by RohDonghyeon** [mileyan/pseudo_lidar#29]
Unable to decompress file finetune_300.tar
If i try to decompress, it is not a compressed file.
What should i do if i try to decompress?

**Comment by mileyan** [comment]
Hi,
Sorry about that. I did not explain it clearly. Even though the suffix is 'tar', but it is not a compressed file. You don't have to decompress it. You can directly load it using torch.load().

**Comment by RohDonghyeon** [comment]
Aha! Thank you for the explanation!
