### ISSUE TITLE
When will the code be released?

### ISSUE THREAD

**Issue by liamlin88** [mileyan/pseudo_lidar#3]
Your research is very interesting! So I wanna talk about it in the presentation of my auto drive class. Of course, it will be better if I can get the code and reproduce it. Thx!

**Comment by mileyan** [comment]
Hi Liamlin,

Thanks for your interest. I am trying to clean the code and organize pre-trained models this week. It might be released end of this week. Hope it can help you.

Best

**Comment by liamlin88** [comment]
> Hi Liamlin,
> Thanks for your interest. I am trying to clean the code and organize pre-trained models this week. It might be released end of this week. Hope it can help you.
> Best

Thank you very much!!
