### ISSUE TITLE
How can i visualize a bin file?

### ISSUE THREAD

**Issue by RohDonghyeon** [mileyan/pseudo_lidar#30]
Currently, the .npy file of predict_disparity is visualized and checked visually, but i can't figure out how to visualize pseudo-lidar_velodyne's bin file.

Can you tell me how to visualize?

**Comment by AsiDiaz** [comment]
Hi @RohDonghyeon, how did you achieve the visualization o the bin file?

**Comment by stanny880913** [comment]
> Hi @RohDonghyeon, how did you achieve the visualization o the bin file?
Hello, you can use open3D to visualize it !!
