### ISSUE TITLE
pseudo lidar

### ISSUE THREAD

**Issue by linchunmian** [mileyan/pseudo_lidar#44]
Hi, could you please provide the generated pseudo lidar of training and testing data in another way? The file is too big to not pull from Google drive. Or you can place it in Baiduyundisk?
Sorry, I come from China, except from Baiduyundisk, I don't have better option that can download such large data.

Thanks again for your great job!

**Comment by mileyan** [comment]
Hi, you can download the pretrained model. And follow the readme from section 2.5 to generate the pseudo lidar point cloud by yourselves. The pretrained model is not too large. If you have any question, please let me know,
