### ISSUE TITLE
pseudo lidar gives wrong converted point cloud

### ISSUE THREAD

**Issue by sarimmehdi** [mileyan/pseudo_lidar#45]
Hello. This is a KITTI image:

![000000](https://user-images.githubusercontent.com/36595832/89733270-b232c080-da54-11ea-92ff-87cdefc5dc91.png)

And this is its depth map obtained using MADNet

![000000](https://user-images.githubusercontent.com/36595832/89733263-9e875a00-da54-11ea-80ec-f6c045720c88.png)

But this is its point cloud when generated using your code:

![incorrect](https://user-images.githubusercontent.com/36595832/89733307-e73f1300-da54-11ea-99ec-32ca96284880.png)

Please tell me what could be going wrong here. The depth map looks reasonably good but the generated point cloud doesn't (I used preprocessing/generate_lidar.py)

**Comment by mileyan** [comment]
could you send your depth map file and file id to yw763@cornell.edu. I can help you check it.
