### ISSUE TITLE
Can not install pytorch with Python 2.7

### ISSUE THREAD

**Issue by zazicky** [mileyan/pseudo_lidar#46]
Is there a solution to  **conda install pytorch==0.4.1 torchvision==0.2.1 cuda92 -c pytorch** with Python 2.7 on Windows10? 
If not, how can I run the disparity step 2.5 (https://github.com/mileyan/pseudo_lidar)? It is possible to install  **conda install pytorch==0.4.1 torchvision==0.2.1 cuda92 -c pytorch** under python 3.6 but then I get a lot of errors when I try to run submission.py (see below) since code is written for python 2.7 I think. 

Traceback (most recent call last):
  File "submission.py", line 57, in <module>
    test_left_img, test_right_img = DA.dataloader(args.datapath)
  File "\KITTI\psmnet\dataloader\KITTI_submission_loader.py", line 26, in dataloader
    image = [img for img in os.listdir(filepath+left_fold)]
FileNotFoundError: [WinError 3] The system cannot find the path specified: '/scratch/datasets/kitti2015/testing/image_2/

**Comment by Hira63S** [comment]
Try to create a conda environment and install pytorch in that.

**Comment by mileyan** [comment]
@zazicky 
Please run the commands to create a conda env.
```
conda create -n py27 python=2.7
conda activcate py27
conda install pytorch==0.4.0 torchvision==0.2.0 cuda92 -c pytorch
```
Please let me know if you have any questions.

Thank @Hira63S
