### ISSUE TITLE
Calibration data for test data

### ISSUE THREAD

**Issue by zsfVishnu** [mileyan/pseudo_lidar#5]
1) Are you using the calibration parameters for test data too, like how you used for point cloud generation? < [generate_lidar](https://github.com/mileyan/pseudo_lidar/blob/master/preprocessing/generate_lidar.py) >
2) Also , could you give an idea as to what the 'Tr_velo_to_cam' parameter is ? <[kitti_util](https://github.com/mileyan/pseudo_lidar/blob/master/preprocessing/kitti_util.py) > 

Thank You.

**Comment by mileyan** [comment]
Hi,

1. Yes. We use the calibration files inside the testing folder to generate test point clouds. You can simply modify the `calib_dir`.

2. This is the projection matrix from velodyne to camera coordinate.

**Comment by zsfVishnu** [comment]
@mileyan , thank you for your reply.
I understand that the calibration file is generated for individual images of Kitti. Is it possible for an alternative to these calibration files,or a way for generating these for our custom data as well.
Thank You

**Comment by mileyan** [comment]
Yes, you can generate the calibration files for your custom data. You can try to use this tool http://www.cvlibs.net/software/calibration/ .

**Comment by Haawron** [comment]
> Yes, you can generate the calibration files for your custom data. You can try to use this tool http://www.cvlibs.net/software/calibration/ .

Hi, that link seems to be dead. Did you keep that tool on your local and could you share?
I have searched for a while but i cannot find any breakthroughs...

EDIT:
How can I get `P2`, `R0_rect` and `Tr_velo_to_cam` matrices?

**Comment by SoulProficiency** [comment]
> > Yes, you can generate the calibration files for your custom data. You can try to use this tool http://www.cvlibs.net/software/calibration/ .
> 
> Hi, that link seems to be dead. Did you keep that tool on your local and could you share? I have searched for a while but i cannot find any breakthroughs...
> 
> EDIT: How can I get `P2`, `R0_rect` and `Tr_velo_to_cam` matrices?

have you slove this problem？
