### ISSUE TITLE
Generate bad disparity map

### ISSUE THREAD

**Issue by godspeed1989** [mileyan/pseudo_lidar#7]
Hi, Yan.
Thanks for your great work.

I am using pytorch 1.1.0.

I follow the readme to generate disparity and point cloud.
First, i download your pretrained PSMNet model.
Then, i run following cmd to generate disparity.
```
$ python ./psmnet/submission.py --loadmodel ./finetune_300.tar --datapath /mine/KITTI_DAT/training/ --save_path ./training_predict_disparity/
Number of model parameters: 5224768
/usr/lib/python3.7/site-packages/torch/nn/functional.py:2457: UserWarning: nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.")
/usr/lib/python3.7/site-packages/torch/nn/functional.py:2539: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
/usr/lib/python3.7/site-packages/torch/nn/functional.py:2539: UserWarning: Default upsampling behavior when mode=trilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
time = 1.18
000000.png
time = 0.42
000001.png
time = 0.42
000002.png
...
```
Next, i run following cmd to generate point cloud *.bin
```
$ python ./preprocessing/generate_lidar.py --calib_dir /mine/KITTI_DAT/training/calib/ --save_dir ./training_predict_velodyne/ --disparity_dir ./training_predict_disparity/ --max_high 1
Finish Depth 000000
Finish Depth 000001
Finish Depth 000002
Finish Depth 000003
Finish Depth 000004
...
```
However, i got disparity map for `training/000002` like this:
![000002](https://user-images.githubusercontent.com/2350713/60496198-e5007600-9ce4-11e9-9c31-14e2cf6686ba.png)
and point cloud like this:
![image](https://user-images.githubusercontent.com/2350713/60496462-6f48da00-9ce5-11e9-83de-c5646cb2c6eb.png)
The RGB image is:
![000002l](https://user-images.githubusercontent.com/2350713/60496778-16c60c80-9ce6-11e9-9c26-d0e4993087b3.png)

I think the generated disparity is bad. But i can't figure out the reason.
Thank you

**Comment by mileyan** [comment]
Can you please check the PSMNet environment? 
Python2.7
PyTorch(0.4.0+)
torchvision 0.2.0 (higher version may cause issues)

**Comment by godspeed1989** [comment]
Hi,
I am using python3 and pytorch 1.1.0.
Should I retrain PSMNet?
That's wired, is there any simpler solution.
Thank you

**Comment by mileyan** [comment]
The simpler solution is you install Python2.7, PyTorch(0.4.0+), torchvision 0.2. You can easily use anaconda to create a new environment.

**Comment by godspeed1989** [comment]
Thanks.

**Comment by godspeed1989** [comment]
Hi, Is this how it is supposed to be now ? 
![image](https://user-images.githubusercontent.com/2350713/61031478-31893700-a3f2-11e9-9b74-ffba5cdc2f84.png)
![image](https://user-images.githubusercontent.com/2350713/61031540-4e256f00-a3f2-11e9-9b82-52feb92c41b5.png)
![image](https://user-images.githubusercontent.com/2350713/61031617-790fc300-a3f2-11e9-97c3-e0751a07c15c.png)

**Comment by mileyan** [comment]
It should not look like it. How do you generate this point cloud? which code do you use?

**Comment by godspeed1989** [comment]
I follow your README to generate point cloud.
Firstly, generating disparity map
```
$ python ./psmnet/submission.py \
--loadmodel ./finetune_300.tar \
--datapath /mine/KITTI_DAT/training/ \
--save_path ./training_predict_disparity/
```
Then, converting disparity to point cloud
```
python ./preprocessing/generate_lidar.py  \
    --calib_path /mine/KITTI_DAT/training/calib \
    --save_path ./training_predict_velodyne \
    --disparity_dir ./training_predict_disparity/ \
    --max_high 1
```
I notice the `--disp_path` cmd option is incorrect, so i use `--disparity_dir` instead
This is the `000003` file in KITTI training set

**Comment by zklgame** [comment]
I also found the script ```generate_lidar.py ``` does not work properly! 
I used frustum-pointnets, first feed the ground truth velodyne to it for testing, and it worked well. Then I use ```generate_lidar.py ``` to generate predicted_velodyne from ground disparity, and feed predicted_velodyne for testing, the results are very bad. So I think there should be some problem in ```generate_lidar.py ```.

**Comment by mileyan** [comment]
> I follow your README to generate point cloud.
> Firstly, generating disparity map
> 
> ```
> $ python ./psmnet/submission.py \
> --loadmodel ./finetune_300.tar \
> --datapath /mine/KITTI_DAT/training/ \
> --save_path ./training_predict_disparity/
> ```
> 
> Then, converting disparity to point cloud
> 
> ```
> python ./preprocessing/generate_lidar.py  \
>     --calib_path /mine/KITTI_DAT/training/calib \
>     --save_path ./training_predict_velodyne \
>     --disparity_dir ./training_predict_disparity/ \
>     --max_high 1
> ```
> 
> I notice the `--disp_path` cmd option is incorrect, so i use `--disparity_dir` instead
> This is the `000003` file in KITTI training set

Hi godspeed1989,

I used the code in this repo to generate the point cloud. It looks correct. Not sure why your result is not right. So Can you send me the disparity file and bin file of 000003 to me? My email is yw763@cornell.edu . Thanks.

**Comment by mileyan** [comment]
> I also found the script `generate_lidar.py ` does not work properly!
> I used frustum-pointnets, first feed the ground truth velodyne to it for testing, and it worked well. Then I use `generate_lidar.py ` to generate predicted_velodyne from ground disparity, and feed predicted_velodyne for testing, the results are very bad. So I think there should be some problem in `generate_lidar.py `.

Hi zklgame,

Did you use the FPointNet trained on velodyne or on pseudo-lidar? Might you try this checkpoint https://drive.google.com/file/d/1qhCxw6uHqQ4SAkxIuBi-QCKqLmTGiNhP/view?usp=sharing, which is trained on pseudo-lidar.

**Comment by godspeed1989** [comment]
Hi, mileyan.
I add `--save_float`option to run `python ./psmnet/submission.py` and generate disparity map stored in npy.
In the meanwhile, modified serveral lines in `./preprocessing/generate_lidar.py` to read .npy instead of .png.
The result looks better.
training/000000
![image](https://user-images.githubusercontent.com/2350713/62033621-f0c95480-b21e-11e9-9137-5f6221b7729c.png)
training/000002
![image](https://user-images.githubusercontent.com/2350713/62033733-2e2de200-b21f-11e9-8512-0ea86d3ea8f5.png)
training/000003
![image](https://user-images.githubusercontent.com/2350713/62033795-5ddcea00-b21f-11e9-8c47-9f44490bd1a8.png)

**Comment by mileyan** [comment]
Hi godspeed1989,

It looks great! I will change the `save_float` to the default setting. Thanks for your feedback.

**Comment by swdev1202** [comment]
@godspeed1989 
May I ask you what visualization tool you use for the point cloud (.bin)?

Thank you!

**Comment by godspeed1989** [comment]
@swdev1202 
I am using `pyqtgraph` to visual point cloud.
You can install it use pip
```
from pyqtgraph.Qt import QtCore, QtGui
import pyqtgraph.opengl as gl

class plot3d(object):
    def __init__(self, title='null'):
        #
        self.glview = gl.GLViewWidget()
        coord = gl.GLAxisItem()
        coord.setSize(1,1,1)
        #self.glview.addItem(coord)
        self.glview.setMinimumSize(QtCore.QSize(600, 500))
        self.glview.pan(1, 0, 0)
        self.glview.setCameraPosition(azimuth=180)
        self.glview.setCameraPosition(elevation=0)
        self.glview.setCameraPosition(distance=5)
        self.items = []
        #
        self.view = QtGui.QWidget()
        self.view.window().setWindowTitle(title)
        hlayout = QtGui.QHBoxLayout()
        snap_btn = QtGui.QPushButton('&Snap')
        def take_snap():
            qimg = self.glview.readQImage()
            qimg.save('1.jpg')
        snap_btn.clicked.connect(take_snap)
        hlayout.addWidget(snap_btn)
        hlayout.addStretch()
        layout = QtGui.QVBoxLayout()
        #
        layout.addLayout(hlayout)
        layout.addWidget(self.glview)
        self.view.setLayout(layout)
    def add_item(self, item):
        self.glview.addItem(item)
        self.items.append(item)
    def clear(self):
        for it in self.items:
            self.glview.removeItem(it)
        self.items.clear()
    def add_points(self, points, colors):
        points_item = gl.GLScatterPlotItem(pos=points, size=1.5, color=colors)
        self.add_item(points_item)
    def add_line(self, p1, p2, color, width=3):
        lines = np.array([[p1[0], p1[1], p1[2]],
                          [p2[0], p2[1], p2[2]]])
        lines_item = gl.GLLinePlotItem(pos=lines, mode='lines',
                                       color=color, width=width, antialias=True)
        self.add_item(lines_item)
    def plot_bbox_mesh(self, gt_boxes3d, color=(0,1,0,1)):
        b = gt_boxes3d
        for k in range(0,4):
            i,j=k,(k+1)%4
            self.add_line([b[i,0],b[i,1],b[i,2]], [b[j,0],b[j,1],b[j,2]], color)
            i,j=k+4,(k+1)%4 + 4
            self.add_line([b[i,0],b[i,1],b[i,2]], [b[j,0],b[j,1],b[j,2]], color)
            i,j=k,k+4
            self.add_line([b[i,0],b[i,1],b[i,2]], [b[j,0],b[j,1],b[j,2]], color)

def value_to_rgb(pc_inte):
    minimum, maximum = np.min(pc_inte), np.max(pc_inte)
    ratio = (pc_inte - minimum + 0.1) / (maximum - minimum + 0.1)
    r = (np.maximum((1 - ratio), 0))
    b = (np.maximum((ratio - 1), 0))
    g = 1 - b - r
    return np.stack([r, g, b]).transpose()

def view_points_cloud(pc=None):
    app = QtGui.QApplication([])
    glview = plot3d()
    if pc is None:
        pc = np.random.rand(1024, 3)
    pc_color = np.ones([pc.shape[0], 4])
    glview.add_points(pc, pc_color)
    glview.view.show()
    return app.exec()
```

**Comment by Tantoyy** [comment]
@godspeed1989 
godspeed1989  Hi,How does this code apply and where do I need to put it?

**Comment by DavidDiosdado** [comment]
> @swdev1202
> I am using `pyqtgraph` to visual point cloud.
> You can install it use pip
> 
> ```
> from pyqtgraph.Qt import QtCore, QtGui
> import pyqtgraph.opengl as gl
> 
> class plot3d(object):
>     def __init__(self, title='null'):
>         #
>         self.glview = gl.GLViewWidget()
>         coord = gl.GLAxisItem()
>         coord.setSize(1,1,1)
>         #self.glview.addItem(coord)
>         self.glview.setMinimumSize(QtCore.QSize(600, 500))
>         self.glview.pan(1, 0, 0)
>         self.glview.setCameraPosition(azimuth=180)
>         self.glview.setCameraPosition(elevation=0)
>         self.glview.setCameraPosition(distance=5)
>         self.items = []
>         #
>         self.view = QtGui.QWidget()
>         self.view.window().setWindowTitle(title)
>         hlayout = QtGui.QHBoxLayout()
>         snap_btn = QtGui.QPushButton('&Snap')
>         def take_snap():
>             qimg = self.glview.readQImage()
>             qimg.save('1.jpg')
>         snap_btn.clicked.connect(take_snap)
>         hlayout.addWidget(snap_btn)
>         hlayout.addStretch()
>         layout = QtGui.QVBoxLayout()
>         #
>         layout.addLayout(hlayout)
>         layout.addWidget(self.glview)
>         self.view.setLayout(layout)
>     def add_item(self, item):
>         self.glview.addItem(item)
>         self.items.append(item)
>     def clear(self):
>         for it in self.items:
>             self.glview.removeItem(it)
>         self.items.clear()
>     def add_points(self, points, colors):
>         points_item = gl.GLScatterPlotItem(pos=points, size=1.5, color=colors)
>         self.add_item(points_item)
>     def add_line(self, p1, p2, color, width=3):
>         lines = np.array([[p1[0], p1[1], p1[2]],
>                           [p2[0], p2[1], p2[2]]])
>         lines_item = gl.GLLinePlotItem(pos=lines, mode='lines',
>                                        color=color, width=width, antialias=True)
>         self.add_item(lines_item)
>     def plot_bbox_mesh(self, gt_boxes3d, color=(0,1,0,1)):
>         b = gt_boxes3d
>         for k in range(0,4):
>             i,j=k,(k+1)%4
>             self.add_line([b[i,0],b[i,1],b[i,2]], [b[j,0],b[j,1],b[j,2]], color)
>             i,j=k+4,(k+1)%4 + 4
>             self.add_line([b[i,0],b[i,1],b[i,2]], [b[j,0],b[j,1],b[j,2]], color)
>             i,j=k,k+4
>             self.add_line([b[i,0],b[i,1],b[i,2]], [b[j,0],b[j,1],b[j,2]], color)
> 
> def value_to_rgb(pc_inte):
>     minimum, maximum = np.min(pc_inte), np.max(pc_inte)
>     ratio = (pc_inte - minimum + 0.1) / (maximum - minimum + 0.1)
>     r = (np.maximum((1 - ratio), 0))
>     b = (np.maximum((ratio - 1), 0))
>     g = 1 - b - r
>     return np.stack([r, g, b]).transpose()
> 
> def view_points_cloud(pc=None):
>     app = QtGui.QApplication([])
>     glview = plot3d()
>     if pc is None:
>         pc = np.random.rand(1024, 3)
>     pc_color = np.ones([pc.shape[0], 4])
>     glview.add_points(pc, pc_color)
>     glview.view.show()
>     return app.exec()
> ```

How can I use this code to visualize my bin files?

**Comment by godspeed1989** [comment]
@Tantoyy @DavidDiosdado you can call `view_points_cloud()` to display your (N,3) points array

**Comment by lilingge** [comment]
> Hi, Yan.
> Thanks for your great work.
> 
> I am using pytorch 1.1.0.
> 
> I follow the readme to generate disparity and point cloud.
> First, i download your pretrained PSMNet model.
> Then, i run following cmd to generate disparity.
> 
> ```
> $ python ./psmnet/submission.py --loadmodel ./finetune_300.tar --datapath /mine/KITTI_DAT/training/ --save_path ./training_predict_disparity/
> Number of model parameters: 5224768
> /usr/lib/python3.7/site-packages/torch/nn/functional.py:2457: UserWarning: nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.
>   warnings.warn("nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.")
> /usr/lib/python3.7/site-packages/torch/nn/functional.py:2539: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
>   "See the documentation of nn.Upsample for details.".format(mode))
> /usr/lib/python3.7/site-packages/torch/nn/functional.py:2539: UserWarning: Default upsampling behavior when mode=trilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
>   "See the documentation of nn.Upsample for details.".format(mode))
> time = 1.18
> 000000.png
> time = 0.42
> 000001.png
> time = 0.42
> 000002.png
> ...
> ```
> 
> Next, i run following cmd to generate point cloud *.bin
> 
> ```
> $ python ./preprocessing/generate_lidar.py --calib_dir /mine/KITTI_DAT/training/calib/ --save_dir ./training_predict_velodyne/ --disparity_dir ./training_predict_disparity/ --max_high 1
> Finish Depth 000000
> Finish Depth 000001
> Finish Depth 000002
> Finish Depth 000003
> Finish Depth 000004
> ...
> ```
> 
> However, i got disparity map for `training/000002` like this:
> ![000002](https://user-images.githubusercontent.com/2350713/60496198-e5007600-9ce4-11e9-9c31-14e2cf6686ba.png)
> and point cloud like this:
> ![image](https://user-images.githubusercontent.com/2350713/60496462-6f48da00-9ce5-11e9-83de-c5646cb2c6eb.png)
> The RGB image is:
> ![000002l](https://user-images.githubusercontent.com/2350713/60496778-16c60c80-9ce6-11e9-9c26-d0e4993087b3.png)
> 
> I think the generated disparity is bad. But i can't figure out the reason.
> Thank you

Hi, I'm using torch0.4.1and torchvision0.2.1 python3.7. However I still get bad result like your's result. Which version do you use?

**Comment by lilingge** [comment]
> @Tantoyy @DavidDiosdado you can call `view_points_cloud()` to display your (N,3) points array

Hi,  In view_points_cloud(), how to transfer the depth bin file into the parameter "pc"?

**Comment by mileyan** [comment]
Hi @lilingge , I have add a jupyter script for visualization in the folder ./visualization. Hope it can help you.

**Comment by lilingge** [comment]
> Hi @lilingge , I have add a jupyter script for visualization in the folder ./visualization. Hope it can help you.

Hi, author,  the code is very useful! But I still have a question, how do I save the Cloud as png?

**Comment by mileyan** [comment]
I usually take a screenshot. Or you can use PPTK library https://github.com/heremaps/pptk.

**Comment by lilingge** [comment]
> I usually take a screenshot. Or you can use PPTK library https://github.com/heremaps/pptk.

Emmm, I get trouble in showing cloud. I can't get expected interface as your show and I reopen my web browser but not make difference.  What should I do?

**Comment by mileyan** [comment]
Hi, have you installed the requirements? `pip install pythreejs pyntcloud pandas numpy`

**Comment by lilingge** [comment]
The question is solved!  Thank you very much! It's something else, not the requirements.

**Comment by rsj007** [comment]
> Hi, mileyan. I add `--save_float`option to run `python ./psmnet/submission.py` and generate disparity map stored in npy. In the meanwhile, modified serveral lines in `./preprocessing/generate_lidar.py` to read .npy instead of .png. The result looks better. training/000000 ![image](https://user-images.githubusercontent.com/2350713/62033621-f0c95480-b21e-11e9-9137-5f6221b7729c.png) training/000002 ![image](https://user-images.githubusercontent.com/2350713/62033733-2e2de200-b21f-11e9-8512-0ea86d3ea8f5.png) training/000003 ![image](https://user-images.githubusercontent.com/2350713/62033795-5ddcea00-b21f-11e9-8c47-9f44490bd1a8.png)
> 
> But i not sure whether it is correct now. I notice the estimated depth is not so good at the distance.

Hi, I don't find "save_float" in submission.py. Do you mean "save_figure" instead?

**Comment by rsj007** [comment]
> The question is solved! Thank you very much! It's something else, not the requirements.

Hello, I cannot visualize the point cloud as the interface. How to solve it? Thanks!!!

**Comment by a-free-a** [comment]
> 嗨，这就是它应该是现在？ ![image](https://user-images.githubusercontent.com/2350713/61031478-31893700-a3f2-11e9-9b74-ffba5cdc2f84.png) ![image](https://user-images.githubusercontent.com/2350713/61031540-4e256f00-a3f2-11e9-9b82-52feb92c41b5.png) ![image](https://user-images.githubusercontent.com/2350713/61031617-790fc300-a3f2-11e9-97c3-e0751a07c15c.png) 但是，我注意到所产生的伪点云似乎没有类似于那些在你的论文

Hello, I encountered the same problem as you did. The pseudo-point cloud I generated is also sliced. Could you please tell me how you solved this problem? Thank you.

**Comment by a-free-a** [comment]
> Hi, Is this how it is supposed to be now ? ![image](https://user-images.githubusercontent.com/2350713/61031478-31893700-a3f2-11e9-9b74-ffba5cdc2f84.png) ![image](https://user-images.githubusercontent.com/2350713/61031540-4e256f00-a3f2-11e9-9b82-52feb92c41b5.png) ![image](https://user-images.githubusercontent.com/2350713/61031617-790fc300-a3f2-11e9-97c3-e0751a07c15c.png) But, I notice the generated pseudo point cloud seems not similar to the ones in your papers

Hello, I encountered the same problem as you did. The pseudo-point cloud I generated is also sliced. Could you please tell me how you solved this problem? Thank you.
