### ISSUE TITLE
Confusion in GT Disparity Map

### ISSUE THREAD

**Issue by rishimadhok** [mileyan/pseudo_lidar#9]
Hi authors, 

Thank you so much for providing the code for your paper. I have a query regarding the GT Disparity map that you generate using `./preprocessing/generate_disp.py`

I downloaded the GT Disparity that you provided. However, it looks more like a LIDAR point cloud than a disparity image. Is this how it is supposed to be? I plotted the below GT using matplotlib
![WhatsApp Image 2019-07-08 at 12 59 31 PM](https://user-images.githubusercontent.com/17377540/60829582-3300f800-a183-11e9-9be6-ea76c45af53b.jpeg)

RGB image for the above GT disparity map is given below
![WhatsApp Image 2019-07-08 at 11 55 33 AM](https://user-images.githubusercontent.com/17377540/60829644-57f56b00-a183-11e9-9b1f-117160bf0f66.jpeg)

Please let me know. Thank you!

**Comment by mileyan** [comment]
Hi Rishi,
Yes, The disparity is correct. This disparity map is generated by LiDAR point cloud, that is the reason it looks very sparse.
